version: '3'
services:
    php:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: shopxophp:latest
        container_name: php
        restart: always
    web:
        build: 
            context: .
            dockerfile: ./Nginx.Dockerfile
        image: shopxonginx:latest
        container_name: web
        ports:
            - "8081:80"
            - "8082:443"
        restart: always
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - php